language: node_js
node_js:
  - "7"
dist: trusty # needs Ubuntu Trusty
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn run travis
notifications:
  webhooks: https://44999c08.ngrok.io/api/v2/webhooks/travisci
